version: 2.1

aliases:
  - &restore-cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &install-deps
    run:
      name: Install Dependencies
      command: yarn install --ignore-scripts --frozen-lockfile --cache-folder ~/.cache/yarn
  - &install-bullmq-version
    run:
      name: Install bullmq version
      command: yarn workspace @nestjs/bullmq add --dev bullmq@$BULLMQ_VERSION --force --ignore-scripts
  - &build-packages
    run:
      name: Build
      command: yarn build
  - &save-cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: cimg/node:24.20.0
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Build
          command: yarn build

  unit_tests:
    parameters:
      bullmq-version:
        type: string
        default: ""
    working_directory: ~/nest
    docker:
      - image: cimg/node:24.20.0
    environment:
      BULLMQ_VERSION: << parameters.bullmq-version >>
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - when:
          condition: << parameters.bullmq-version >>
          steps:
            - *install-bullmq-version
      - run:
          name: Unit tests
          command: yarn test

  integration_tests:
    parameters:
      bullmq-version:
        type: string
        default: ""
    working_directory: ~/nest
    machine:
      image: ubuntu-2204:current
    environment:
      BULLMQ_VERSION: << parameters.bullmq-version >>
    steps:
      - checkout
      - run:
          name: Prepare Node.js
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            source $BASH_ENV
            nvm install v24.19.0
            nvm alias default v24.19.0
            echo 'nvm use default > /dev/null || true' >> $BASH_ENV
      - run:
          name: Install Yarn
          command: |
            npm install -g yarn
            node -v
            yarn -v
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - *install-deps
      - when:
          condition: << parameters.bullmq-version >>
          steps:
            - *install-bullmq-version
      - run:
          name: Prepare
          command: |
            docker-compose up -d
            sleep 10
      - run:
          name: List containers
          command: docker ps
      - run:
          name: e2e tests
          command: yarn test:e2e

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit_tests:
          matrix:
            parameters:
              bullmq-version:
                - "5.81.3"
                - "6.0.9"
          requires:
            - build
      - integration_tests:
          matrix:
            parameters:
              bullmq-version:
                - "5.81.3"
                - "6.0.9"
          requires:
            - build
